name: hurricane-gliders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.2
  - netcdf4=1.5.3
  - numpy=1.18.1
  - pandas=1.0.4
  - xarray=0.15.1
  - cartopy=0.18.0
  - matplotlib=3.3.4
  - cmocean=2.0
  - erddapy=0.4.0
  - motuclient=1.8.8
